### ISSUE TITLE
未安装协议支持

### ISSUE THREAD

**Issue by Talaxy009** [ysc3839/luci-proto-minieap#1]
用的是大佬的V2.1-1的版本，已经安装了V0.92.1的MiniEAP，但在更换接口协议为"MiniEAP 客户端"后下面仍会提示“未安装协议支持 [INSTALL PACKAGE 'MINIEAP']”

**Comment by ysc3839** [comment]
重启试试？

**Comment by Talaxy009** [comment]
嗯，还是一样呀。试了下minieap -h是有反应的，minieap应该是可以正常运行的，不知道luci那能不能正常运行（即便有这个提示），等回学校试试看

**Comment by ysc3839** [comment]
那我也不知道是什么问题了。

**Comment by Talaxy009** [comment]
昂，可以了，换用了大佬的0.92.1-4的minieap就正常了，之前用的还是你在18年发到GZHU-Dress的，顺便请问下你的minieap带gzhu后缀的和不带的有什么区别吗？

**Comment by ysc3839** [comment]
区别在这 https://github.com/ysc3839/openwrt-minieap/blob/gzhu/patches/006-minieap-gzhu.patch

**Comment by Talaxy009** [comment]
好的，谢谢大佬！
